version: "3.6"
services:
  app:
    build: .
    depends_on:
      - postgres
      - hasura
      - soruce-db
      - destination-db
    env_file:
      - .env
    volumes:
      - "./:/app"
      - "./.docker-data/app/vscode-server:/root/.vscode-server"
    environment:
      SOURCE_DB_CONNSTR: Driver={ODBC Driver 18 for SQL Server};Server=tcp:soruce-db,1433;Database=master;Uid=sa;Pwd=Passw0rd!12345;Encrypt=yes;TrustServerCertificate=yes;
      DESTINATION_DB_CONNSTR: Driver={ODBC Driver 18 for SQL Server};Server=tcp:destination-db,1433;Database=master;Uid=sa;Pwd=Passw0rd!12345;Encrypt=yes;TrustServerCertificate=yes;
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./.docker-data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: db
  redis:
    image: redis/redis-stack
    ports:
      - "${REDIS_UI_PORT}:8001"
    volumes:
      - ./.docker-data/redis:/data
  soruce-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "${SOURCE_DB_PORT}:1433"
    volumes:
      - ./sql/source:/scripts
      - ./.docker-data/soruce-db:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Passw0rd!12345
    command:
      - /bin/bash
      - -c
      - |
        # Launch MSSQL and send to background
        /opt/mssql/bin/sqlservr &
        pid=$!
        # Wait for it to be available
        echo "Waiting for MS SQL to be available"
        /opt/mssql-tools/bin/sqlcmd -l 30 -S localhost -h-1 -V1 -U sa -P $$SA_PASSWORD -Q "SET NOCOUNT ON SELECT \"YAY WE ARE UP\" , @@servername"
        is_up=$$?
        while [ $$is_up -ne 0 ] ; do 
          echo -e $$(date) 
          /opt/mssql-tools/bin/sqlcmd -l 30 -S localhost -h-1 -V1 -U sa -P $$SA_PASSWORD -Q "SET NOCOUNT ON SELECT \"YAY WE ARE UP\" , @@servername"
          is_up=$$?
          sleep 5 
        done
        # Run every script in /scripts
        for foo in /scripts/*.sql
          do /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -l 30 -e -i $$foo
        done
        # trap SIGTERM and send same to sqlservr process for clean shutdown
        trap "kill -15 $$pid" SIGTERM
        # Wait on the sqlserver process
        wait $$pid
        exit 0

  destination-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "${DESTINATION_DB_PORT}:1433"
    volumes:
      - ./sql/destination:/scripts
      - ./.docker-data/destination-db:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Passw0rd!12345
    command:
      - /bin/bash
      - -c
      - |
        # Launch MSSQL and send to background
        /opt/mssql/bin/sqlservr &
        pid=$!
        # Wait for it to be available
        echo "Waiting for MS SQL to be available"
        /opt/mssql-tools/bin/sqlcmd -l 30 -S localhost -h-1 -V1 -U sa -P $$SA_PASSWORD -Q "SET NOCOUNT ON SELECT \"YAY WE ARE UP\" , @@servername"
        is_up=$$?
        while [ $$is_up -ne 0 ] ; do 
          echo -e $$(date) 
          /opt/mssql-tools/bin/sqlcmd -l 30 -S localhost -h-1 -V1 -U sa -P $$SA_PASSWORD -Q "SET NOCOUNT ON SELECT \"YAY WE ARE UP\" , @@servername"
          is_up=$$?
          sleep 5 
        done
        # Run every script in /scripts
        for foo in /scripts/*.sql
          do /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -l 30 -e -i $$foo
        done
        # trap SIGTERM and send same to sqlservr process for clean shutdown
        trap "kill -15 $$pid" SIGTERM
        # Wait on the sqlserver process
        wait $$pid
        exit 0

  hasura:
    image: hasura/graphql-engine:v2.27.0.cli-migrations-v3
    depends_on:
      - postgres
      - soruce-db
    ports:
      - ${HASURA_PORT}:8080
    volumes:
      - ./hasura/metadata:/hasura-metadata
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/db
      ## this env var can be used to add the above ms sql server database to Hasura as a data source. this can be removed/updated based on your needs
      MSSQL_DATABASE_URL: Driver={ODBC Driver 18 for SQL Server};Server=tcp:soruce-db,1433;Database=master;Uid=sa;Pwd=Passw0rd!12345;Encrypt=yes;TrustServerCertificate=yes;
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: secret
volumes:
  pg_data:
  mssql_data:
